#!/usr/bin/python3.8
import sys
import os

def patch_fn():
    if(len(sys.argv) != 2):
        return sys.exit(1)
    print(sys.argv[1])
    url = sys.argv[1]
    wget_cmd = "wget -P patches/ "+url
    print(wget_cmd)
    os.system(wget_cmd)
    file_name = url[url.rindex("/"):]
    apply_cmd = "patch -p1 < patches"+file_name
    print(apply_cmd)
    os.system(apply_cmd)
    return sys.exit(0)

def main():
    print("Inside Main")
    patch_fn()

if __name__ == "__main__":
    main()
